# -*- coding: utf-8 -*-
"""AI PLAG CHECK PROJECT_SEEMA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mw_34knl90JU1Oz0r8TU8f0KGU69Stsp
"""

!pip install datasets
from datasets import load_dataset
import pandas as pd

# Load dataset
ds = load_dataset("shahxeebhassan/human_vs_ai_sentences")

# Convert to pandas DataFrame
df = pd.DataFrame(ds['train'])  # only 'train' split is available
print(df.head())

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    df['text'], df['label'], test_size=0.2, random_state=42
)

from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(max_features=5000)
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train_vec, y_train)

from sklearn.metrics import classification_report
y_pred = model.predict(X_test_vec)
print(classification_report(y_test, y_pred))

def predict_text_origin(text, model, vectorizer):
    vec = vectorizer.transform([text])
    prediction = model.predict(vec)[0]
    return "AI-generated" if prediction == 1 else "Human-written"

# Example
real_paper_abstract = """Deep neural networks have shown state-of-the-art performance in natural language processing tasks..."""
print(predict_text_origin(real_paper_abstract, model, vectorizer))